apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: fernandoralha/gitops
  newTag: a97b548f895c565e99c996c9c4708e2b148d9ed8
